In [3]:
import numpy as np

In [4]:
x = np.array([1,2,3,4,5])

In [5]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
x.dtype

dtype('int32')

In [7]:
x.shape #this returns the tuple of n-positive integers that specifies the sizes of each dimension
#if it'd be 2-d array, this will return 2 numbers, one is the no of rows and other is column.bb

(5,)

In [8]:
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [9]:
y.shape

(4, 3)

In [10]:
y.size #we refer 1-D array as rank1 array and 2-D array as rank 2 array.b

12

In [11]:
x = np.array(['Helloo','Niki'])

In [12]:
x.dtype #datatype is unicode strings of 5 characters(it stores the maximum one)
#numpy array must contains elements of the same type.

dtype('<U6')

In [13]:
#numpy provides a way to save this array into a file and use later
np.save('my_array',x) #this saves array into a file myarray.npy

In [14]:
y = np.load('my_array.npy')
print(y)

['Helloo' 'Niki']


In [15]:
X = np.zeros((3,4))
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
X = np.zeros((3,4), dtype = int)
print(X)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
X = np.ones((3,4))
print(X)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
X = np.full((3,4),5)
print(X)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [19]:
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
X = np.diag([10,20,30,40])
print(X)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [21]:
X = np.arange(10) #takes three arguments start, stop, step
print(X)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
X = np.linspace(0,25,10)
print(X) #here all the start and end will be inclusive. to not include it, put endpoint = falseb

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [23]:
X = np.reshape(X,(2,5))
print(X) #the value in which you want to reshape must be compatible with the array.

[[ 0.          2.77777778  5.55555556  8.33333333 11.11111111]
 [13.88888889 16.66666667 19.44444444 22.22222222 25.        ]]


In [24]:
X = np.random.randint(4,15,(3,2))
print(X)

[[10  9]
 [13 10]
 [13  8]]


In [25]:
#when you need to create a numpy array that satisfies some statistical properties
X = np.random.normal(0,0.1,size=(1000,1000))
print(X)

[[-1.46385932e-01 -4.40684407e-02 -2.39267832e-02 ... -1.76472156e-02
   1.43371295e-01 -3.88633648e-02]
 [-6.07095244e-03 -4.29000487e-05 -3.28676652e-02 ...  1.58064602e-01
   1.39854552e-01  1.34387463e-01]
 [-1.03535584e-01 -4.66129319e-02  7.91389656e-02 ... -2.92063115e-02
  -1.66562655e-01 -8.62878720e-02]
 ...
 [-6.72289916e-02 -6.95159643e-03  1.20779736e-01 ... -1.18941140e-02
  -1.33850888e-01 -2.25901574e-02]
 [-5.94744588e-02 -2.29422309e-02 -8.78527706e-02 ... -1.97980690e-01
  -1.31152995e-01 -2.76030683e-02]
 [-9.83399168e-02  6.15169736e-02  1.16300818e-01 ...  8.50900763e-02
  -7.03968502e-02  7.61268555e-03]]


In [26]:
#we can use indicies in numpy array both positives and negative

In [27]:
X = np.arange(1,10)
print(X)

X = np.delete(X, [0,8])
print(X)

[1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8]


In [28]:
Y = np.arange(1,10).reshape(3,3)
print(Y)

Y = np.delete(Y,0,axis=0) #axis = 0 means row, 1 means column
print("\n",Y)

Y = np.delete(Y,[0,2],axis=1) #axis = 0 means row, 1 means column
print("\n",Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[5]
 [8]]


In [29]:
X = np.arange(1,10)
print(X)

X = np.append(X,10)
print(X)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
Y = np.arange(1,10).reshape(3,3)
print(Y)

w = np.insert(Y,1,[0,0,0],axis=0)
print("\n",w)

z = np.insert(Y,1,[0,0,0],axis=1)
print("\n",z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 2 3]
 [0 0 0]
 [4 5 6]
 [7 8 9]]

 [[1 0 2 3]
 [4 0 5 6]
 [7 0 8 9]]


In [31]:
#numpy also allows to stack arrays by the top or side by side
# v stack for vertical, h for horizontal
#in order to stack arrays, the shape of the arrays must match

In [32]:
x = np.array([1,2])
y = np.array([[3,4],[5,6]])
z = np.vstack((x,y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [33]:
#similary
z = np.hstack((y,x.reshape(2,1)))
print(z)

[[3 4 1]
 [5 6 2]]


# Slicing


In [34]:
x = np.arange(1,21).reshape(4,5)
print(x)

z = x[1:4,2:5]
print(z) #1:4 indicates what indicies you want to grab from the rows, 2:5 indicates columns

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [35]:
#NOTE: slicing just create a view of the original array and not store the copy of it. so if we change anything to the newer one
#the older one will automatically got affected. to avoid this, we can use copy method of numpy
z = x[1:,2:].copy()
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [36]:
z[2,2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [37]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [38]:
#numpy offers many built-in functions to extract the elements from the array
z = np.diag(x)
print(z)

[ 1  7 13 19]


In [39]:
z = np.diag(x,k=1) #k=1 above the diagonal, if -1, this will extract the value below the main diagonal. Default is 0
print(z)

[ 2  8 14 20]


In [40]:
print(np.unique(x))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# Boolean Operations and Set Operations

In [41]:

print(x[x>10])

[11 12 13 14 15 16 17 18 19 20]


In [42]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,3,10])

print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[2 3]
[1 4 5]
[ 1  2  3  4  5  6  7 10]


In [43]:
#sorting- whenever you use sorting as a function, it will sort out of place else inplace sorting
x = np.random.randint(1,11,size=(10,))
print(x)

[ 2 10  9  7  8 10  6  1  9  2]


In [44]:
print(np.sort(x))
print(x) #sort function

[ 1  2  2  6  7  8  9  9 10 10]
[ 2 10  9  7  8 10  6  1  9  2]


In [45]:
x.sort()
print(x) #sort as a method

[ 1  2  2  6  7  8  9  9 10 10]


In [46]:
print(Y)
    

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
print(np.sort(Y,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Arithmetic Operations 

In [48]:
print(x)
print(y)

[ 1  2  2  6  7  8  9  9 10 10]
[ 6  7  2  3 10]


In [50]:
x = np.array([6,7,2,3,10])

In [51]:
print(np.add(x,y))

[12 14  4  6 20]


In [52]:
print(np.subtract(x,y))

[0 0 0 0 0]


In [53]:
print(np.divide(x,y))

[1. 1. 1. 1. 1.]


In [54]:
print(np.multiply(x,y))

[ 36  49   4   9 100]


In [ ]:
#In order to complete these functions, numpy sometimes use something called as Broadcasting.It is a term used to define how numpy 
#handles arithmetic operations with arrays of different shapes. The arrays must have them the same shape or be broadcastableb

In [55]:
print(np.exp(x))

[4.03428793e+02 1.09663316e+03 7.38905610e+00 2.00855369e+01
 2.20264658e+04]


In [56]:
print(np.sqrt(x))

[2.44948974 2.64575131 1.41421356 1.73205081 3.16227766]


In [57]:
print(np.power(x,2))

[ 36  49   4   9 100]


In [62]:
print("Average of all: ",Y.mean())
print("Average of columns: ",Y.mean(axis=0))
print("Average of rows: ",Y.mean(axis=1))
print("Sum of columns: ",Y.sum(axis=1))

Average of all:  5.0
Average of columns:  [4. 5. 6.]
Average of rows:  [2. 5. 8.]
Sum of columns:  [ 6 15 24]


In [63]:
Y.std()

2.581988897471611

In [64]:
np.median(Y)

5.0

In [65]:
Y.max()

9

In [67]:
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
print(3 + Y)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [69]:
a = np.arange(9).reshape(3,3)
b = np.arange(3)

In [70]:
print(a+b)
#here, the concept of broadcasating is used.

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]
